# Generated by Django 4.0.6 on 2022-07-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_image_slider_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image',
            new_name='Image',
        ),
    ]
