# Generated by Django 4.0.6 on 2022-07-29 07:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Information',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
